name: Release Only (Tag and Trigger)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.2.3)'
        required: true
        type: string

permissions:
  contents: write
  actions: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js (for reading package version)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Read package.json version
        id: pkg
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "PKG_VERSION=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Validate input version matches package.json
        run: |
          VERSION="${{ inputs.version }}"
          PKG_VERSION="${{ steps.pkg.outputs.PKG_VERSION }}"
          if [ "$VERSION" != "$PKG_VERSION" ]; then
            echo "::error::Input version ($VERSION) does not match package.json ($PKG_VERSION)."
            echo "Ensure package.json is already at the intended release version."
            exit 1
          fi

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # NOTE: This workflow does not modify CHANGELOG.md.
      # If no section exists for the version, the Release job will inject a placeholder.

      - name: Check if tag exists on origin
        id: tag_check
        run: |
          VERSION="${{ inputs.version }}"
          if git ls-remote --tags origin "refs/tags/v$VERSION" | grep -q .; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create and push tag
        if: steps.tag_check.outputs.exists == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${{ inputs.version }}"
          git tag -a "v$VERSION" -m "chore(release): v$VERSION"
          git push origin "refs/tags/v$VERSION"

      - name: Trigger release workflow
        if: steps.tag_check.outputs.exists == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'release.yml',
              ref: context.ref,
              inputs: {
                version: '${{ inputs.version }}'
              }
            });

      - name: Summary
        run: |
          if [ "${{ steps.tag_check.outputs.exists }}" = "true" ]; then
            echo "Tag v${{ inputs.version }} already existed. Triggered release.yml via workflow_dispatch instead of creating a new tag."
          else
            echo "Tagged commit $(git rev-parse --short HEAD) as v${{ inputs.version }}."
            echo "This push triggers .github/workflows/release.yml (push: tags: v*)."
          fi
